version: '{build}'
image: Visual Studio 2017
branches:
  only:
  - master
platform:
  - x86
  - x64
  - Any CPU

configuration: DEBUG
before_build:
  - nuget restore

for:
-
  matrix:
    only:
      - image: Visual Studio 2017