version: '1.0.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
  
platform:
  - x86

configuration: DEBUG

before_build:
  - nuget restore

for:
-
  matrix:
    only:
      - image: Visual Studio 2017