version: '1.0.{build}'
image: Visual Studio 2017

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

branches:
  only:
  - master
  
platform:
  - Any CPU

configuration: DEBUG

before_build:
  - nuget restore

for:
-
  matrix:
    only:
      - image: Visual Studio 2017